<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Application Title</title>

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <link rel="stylesheet/less" type="text/css" href="/styles/main.less">
    <script src="/js/less-1.1.3.min.js" type="text/javascript"></script>
    <script src="/js/jquery-1.7.min.js" type="text/javascript"></script>
    <script src="/bootstrap/js/bootstrap-modal.js" type="text/javascript"></script>
    <script src="/bootstrap/js/bootstrap-dropdown.js" type="text/javascript"></script>

  </head>
  <body>
    <div class="container">
      <div class="content">
        <?php
        echo $this->layout()->content
        ?>
      </div>
    </div>
  </body>
</html>